### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by souhailmerroun** [anil-sidhu/react-google-location#2]
I get an error:

Access to fetch at {URL} from origin {URL} has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by Moramu** [comment]
The same issue....

**Comment by souhailmerroun** [comment]
@Moramu you can check my final code If you are still stuck. https://github.com/souhailmerroun/rent-management/blob/master/src/models/RealEstate/SearchAddressFieldGoogleMaps.js

**Comment by ContaMap** [comment]
Guys, it works fine but I am not able to isolate the country data or coordinates coming from the component...I would appreciate any ideas on this matter...tks!

**Comment by Arif1951995** [comment]
Same Issue

**Comment by JasirMJ** [comment]
same issue
